Дз по объектам
PMakagon/HomeWork pull request #7
Opened 2021-09-25 18:16 UTC by PMakagon

Пока минималку сделал,работаю над средней

2021-09-26 08:03 UTC, DisterRU requested changes
В целом хорошо.
Но требуются мелкие правки.

2021-09-26 08:03 UTC, DisterRU commented on src/lesson8/Book.java
> +    private Author authorName;
Это не имя, а полноценный объект автор, который может хранить в себе что угодно, помимо имени (паспорт, права, список книг, рост, вес и тд.). Следовательно, переменная не должна называться authorName, а именно author.

2021-09-26 08:03 UTC, DisterRU commented on src/lesson8/Book.java
> +        return this.year;
В этих методах this можно не писать.

2021-09-26 08:03 UTC, DisterRU commented on src/lesson8/Author.java
> +    }
Вместо одного этого сеттера должны быть два отдельных.
А вот fullName, как раз, должен заполняться на основе двух фамилии и имени.

2021-09-26 08:03 UTC, DisterRU commented on src/lesson8/Author.java
> +    public String fullName ;
private

2021-09-26 10:54 UTC, PMakagon commented on src/lesson8/Author.java
> +    }
Может вообще его убрать, его задача по идее была в том чтобы не писать два сеттера.fullName и так заполняться должен.

2021-09-27 12:15 UTC, DisterRU approved these changes
Хорошо.
Нужно поправить работу с fullName и можно мержить.

2021-09-27 12:15 UTC, DisterRU commented on src/lesson8/Author.java
> +    }
Если мы можем менять имя и фамилию, значит и fullName должен меняться при этом.
Проще всего вообще избавиться от fullName поля и возвращать его в геттере в виде firstName + " " + lastName

2021-09-27 12:33 UTC, merged